name: Policy Checks

on:
  pull_request:

jobs:
  forbid-todo:
    name: forbid-todo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fail if TODO or FIXME found
        run: |
          if grep -RIn "TODO\|FIXME" . \
            --exclude-dir={.git,.github} ; then
            echo "❌ TODO or FIXME found. Please resolve before merging."
            exit 1
          else
            echo "✅ No TODO / FIXME found."
          fi
